services:
  postgres:
    image: postgres:18-alpine
    env_file:
      - ../backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks: [backend]

  redis:
    image: redis:7-alpine
    env_file:
      - ../backend/.env.redis
    ports:
      - "16379:6379"
    networks: [backend]


networks:
  backend:

volumes:
  postgres_data:
